name: Build Android APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 11076708
        packages: "platform-tools platforms;android-33 build-tools;33.0.0 ndk;25.2.9519653"

    - name: Create Android Project
      run: |
        ./build_android.sh

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew

    - name: Build debug APK
      run: |
        cd android
        ./gradlew assembleDebug

    - name: Build release APK (unsigned)
      run: |
        cd android
        ./gradlew assembleRelease

    - name: Upload APK to Release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        gh release upload ${{ github.ref_name }} android/app/build/outputs/apk/debug/app-debug.apk --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}